// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SRJBackend.Infrastructure.Models;

#nullable disable

namespace SRJBackend.Migrations
{
    [DbContext(typeof(SRJDbContext))]
    [Migration("20260505182631_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("role_permissions_pkey");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EventData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("event_data");

                    b.Property<string>("EventType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.HasKey("Id")
                        .HasName("audit_log_pkey");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.ChildbirthType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("childbirth_type_pkey");

                    b.ToTable("childbirth_type", (string)null);
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.CivilState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("civil_state_pkey");

                    b.HasIndex(new[] { "Name" }, "civil_state_name_key")
                        .IsUnique();

                    b.ToTable("civil_state", (string)null);
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("code")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("department_pkey");

                    b.HasIndex(new[] { "Code" }, "department_code_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Name" }, "department_name_key")
                        .IsUnique();

                    b.ToTable("department", (string)null);
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.Disability", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.Property<string>("DisabilityCertificateNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("disability_certificate_number");

                    b.Property<int?>("DisabilityDegreeId")
                        .HasColumnType("integer")
                        .HasColumnName("disability_degree_id");

                    b.Property<int?>("DisabilityTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("disability_type_id");

                    b.Property<bool>("HasDisabilityCertificate")
                        .HasColumnType("boolean")
                        .HasColumnName("has_disability_certificate");

                    b.HasKey("StudentId")
                        .HasName("disabilities_pkey");

                    b.HasIndex("DisabilityDegreeId");

                    b.HasIndex("DisabilityTypeId");

                    b.ToTable("disabilities", (string)null);
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.DisabilityDegree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("degree");

                    b.HasKey("Id")
                        .HasName("disability_degrees_pkey");

                    b.ToTable("disability_degrees", (string)null);
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.DisabilityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("disability_types_pkey");

                    b.ToTable("disability_types", (string)null);
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("code")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("integer")
                        .HasColumnName("province_id");

                    b.HasKey("Id")
                        .HasName("district_pkey");

                    b.HasIndex(new[] { "Code", "ProvinceId" }, "district_code_province_id_key")
                        .IsUnique();

                    b.HasIndex(new[] { "ProvinceId" }, "idx_district_province_id");

                    b.ToTable("district", (string)null);
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.DocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("document_types_pkey");

                    b.HasIndex(new[] { "Name" }, "document_types_name_key")
                        .IsUnique();

                    b.ToTable("document_types", (string)null);
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.EducationalPerson", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<int?>("EthnicSelfIdentificationId")
                        .HasColumnType("integer")
                        .HasColumnName("ethnic_self_identification_id");

                    b.Property<int>("NativeLanguageId")
                        .HasColumnType("integer")
                        .HasColumnName("native_language_id");

                    b.HasKey("PersonId")
                        .HasName("educational_person_pkey");

                    b.HasIndex("EthnicSelfIdentificationId");

                    b.HasIndex("NativeLanguageId");

                    b.ToTable("educational_person", (string)null);
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character(6)")
                        .HasColumnName("code")
                        .IsFixedLength();

                    b.Property<int>("CodeNumber")
                        .HasColumnType("integer")
                        .HasColumnName("code_number");

                    b.Property<int>("GradeOfferingShiftSectionId")
                        .HasColumnType("integer")
                        .HasColumnName("grade_offering_shift_section_id");

                    b.Property<int>("SchoolFeeConceptId")
                        .HasColumnType("integer")
                        .HasColumnName("school_fee_concept_id");

                    b.Property<int?>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("enrollment_pkey");

                    b.HasIndex("GradeOfferingShiftSectionId");

                    b.HasIndex("SchoolFeeConceptId");

                    b.HasIndex("StudentId");

                    b.ToTable("enrollment", (string)null);
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.EthnicSelfIdentification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EthnicSelfIdentification1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ethnic_self_identification");

                    b.HasKey("Id")
                        .HasName("ethnic_self_identifications_pkey");

                    b.ToTable("ethnic_self_identifications", (string)null);
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.Familiar", b =>
                {
                    b.Property<int>("EducationalPersonId")
                        .HasColumnType("integer")
                        .HasColumnName("educational_person_id");

                    b.Property<int?>("LevelOfEducationId")
                        .HasColumnType("integer")
                        .HasColumnName("level_of_education_id");

                    b.Property<bool>("Lives")
                        .HasColumnType("boolean")
                        .HasColumnName("lives");

                    b.Property<string>("Occupation")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("occupation");

                    b.Property<string>("Workplace")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("workplace");

                    b.HasKey("EducationalPersonId")
                        .HasName("familiars_pkey");

                    b.HasIndex("LevelOfEducationId");

                    b.ToTable("familiars", (string)null);
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.FamiliarRelationshipType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("familiar_relationship_type_pkey");

                    b.ToTable("familiar_relationship_type", (string)null);
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.FamiliarStudentRelationship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FamiliarId")
                        .HasColumnType("integer")
                        .HasColumnName("familiar_id");

                    b.Property<int>("FamiliarRelationshipTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("familiar_relationship_type_id");

                    b.Property<bool>("Isguardian")
                        .HasColumnType("boolean")
                        .HasColumnName("isguardian");

                    b.Property<bool>("LivesTogether")
                        .HasColumnType("boolean")
                        .HasColumnName("lives_together");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("familiar_student_relationship_pkey");

                    b.HasIndex("FamiliarId");

                    b.HasIndex("FamiliarRelationshipTypeId");

                    b.HasIndex("StudentId");

                    b.ToTable("familiar_student_relationship", (string)null);
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("genders_pkey");

                    b.HasIndex(new[] { "Name" }, "genders_name_key")
                        .IsUnique();

                    b.ToTable("genders", (string)null);
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('academic_grades_id_seq'::regclass)");

                    b.Property<int>("LevelId")
                        .HasColumnType("integer")
                        .HasColumnName("level_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("academic_grades_pkey");

                    b.HasIndex("LevelId");

                    b.ToTable("grades", (string)null);
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.GradeOffering", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GradeId")
                        .HasColumnType("integer")
                        .HasColumnName("grade_id");

                    b.Property<int>("SchoolYearId")
                        .HasColumnType("integer")
                        .HasColumnName("school_year_id");

                    b.HasKey("Id")
                        .HasName("grade_offerings_pkey");

                    b.HasIndex("GradeId");

                    b.HasIndex("SchoolYearId");

                    b.ToTable("grade_offerings", (string)null);
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.GradeOfferingShift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GradeOfferingId")
                        .HasColumnType("integer")
                        .HasColumnName("grade_offering_id");

                    b.Property<short?>("Sections")
                        .HasColumnType("smallint")
                        .HasColumnName("sections");

                    b.Property<int>("ShiftId")
                        .HasColumnType("integer")
                        .HasColumnName("shift_id");

                    b.HasKey("Id")
                        .HasName("grade_offering_shifts_pkey");

                    b.HasIndex("GradeOfferingId");

                    b.HasIndex("ShiftId");

                    b.ToTable("grade_offering_shifts", (string)null);
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.GradeOfferingShiftSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GradeOfferingShiftId")
                        .HasColumnType("integer")
                        .HasColumnName("grade_offering_shift_id");

                    b.Property<char?>("Section")
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasColumnName("section");

                    b.Property<short?>("SectionNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("section_number");

                    b.HasKey("Id")
                        .HasName("grade_offering_shift_sections_pkey");

                    b.HasIndex("GradeOfferingShiftId");

                    b.ToTable("grade_offering_shift_sections", (string)null);
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.Institution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("name");

                    b.Property<string>("Ruc")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character(11)")
                        .HasColumnName("ruc")
                        .IsFixedLength();

                    b.Property<int>("RucStateId")
                        .HasColumnType("integer")
                        .HasColumnName("ruc_state_id");

                    b.HasKey("Id")
                        .HasName("institution_pkey");

                    b.HasIndex("RucStateId");

                    b.HasIndex(new[] { "Name" }, "institution_name_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Ruc" }, "institution_ruc_key")
                        .IsUnique();

                    b.ToTable("institution", (string)null);
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.InstitutionLevel", b =>
                {
                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("integer")
                        .HasColumnName("institution_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("LevelId")
                        .HasColumnType("integer")
                        .HasColumnName("level_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("LevelId");

                    b.ToTable("institution_levels", (string)null);
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(59)
                        .HasColumnType("character varying(59)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("languages_pkey");

                    b.HasIndex(new[] { "Name" }, "idx_languages_name")
                        .IsUnique();

                    b.ToTable("languages", (string)null);
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.Level", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('academic_levels_id_seq'::regclass)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.HasKey("Id")
                        .HasName("academic_levels_pkey");

                    b.ToTable("levels", (string)null);
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.LevelOfEducation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("level_of_education_pkey");

                    b.HasIndex(new[] { "Name" }, "level_of_education_name_key")
                        .IsUnique();

                    b.ToTable("level_of_education", (string)null);
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("payment_methods_pkey");

                    b.HasIndex(new[] { "Name" }, "payment_methods_name_key")
                        .IsUnique();

                    b.ToTable("payment_methods", (string)null);
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("permissions_pkey");

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<int>("AddressUbigeoId")
                        .HasColumnType("integer")
                        .HasColumnName("address_ubigeo_id");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("CellPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cell_phone");

                    b.Property<int?>("CivilStateId")
                        .HasColumnType("integer")
                        .HasColumnName("civil_state_id");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("document_type_id");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<int>("GenderId")
                        .HasColumnType("integer")
                        .HasColumnName("gender_id");

                    b.Property<string>("IdDocumentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("id_document_number");

                    b.Property<string>("LandlinePhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("landline_phone");

                    b.Property<string>("MaternalLastname")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("maternal_lastname");

                    b.Property<string>("Names")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("names");

                    b.Property<string>("PaternalLastname")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("paternal_lastname");

                    b.Property<int?>("ReligionId")
                        .HasColumnType("integer")
                        .HasColumnName("religion_id");

                    b.HasKey("Id")
                        .HasName("person_pkey");

                    b.HasIndex("AddressUbigeoId");

                    b.HasIndex("CivilStateId");

                    b.HasIndex("GenderId");

                    b.HasIndex("ReligionId");

                    b.HasIndex(new[] { "DocumentTypeId", "IdDocumentNumber" }, "unique_document_type_number")
                        .IsUnique();

                    b.HasIndex(new[] { "IdDocumentNumber" }, "unique_id_document_number")
                        .IsUnique();

                    b.ToTable("person", (string)null);
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("code")
                        .IsFixedLength();

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("province_pkey");

                    b.HasIndex(new[] { "DepartmentId" }, "idx_province_department_id");

                    b.HasIndex(new[] { "Code", "DepartmentId" }, "province_code_department_id_key")
                        .IsUnique();

                    b.ToTable("province", (string)null);
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.Religion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("religion_pkey");

                    b.HasIndex(new[] { "Name" }, "religion_name_key")
                        .IsUnique();

                    b.ToTable("religion", (string)null);
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("roles_pkey");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.RucState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("ruc_states_pkey");

                    b.HasIndex(new[] { "Name" }, "ruc_states_name_key")
                        .IsUnique();

                    b.ToTable("ruc_states", (string)null);
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.SchoolFee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal>("EnrollmentPrice")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("enrollment_price");

                    b.Property<int>("LevelId")
                        .HasColumnType("integer")
                        .HasColumnName("level_id");

                    b.Property<decimal>("RegistrationFee")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("registration_fee");

                    b.Property<int>("SchoolFeeConceptId")
                        .HasColumnType("integer")
                        .HasColumnName("school_fee_concept_id");

                    b.Property<int>("SchoolYearId")
                        .HasColumnType("integer")
                        .HasColumnName("school_year_id");

                    b.Property<int>("ShiftId")
                        .HasColumnType("integer")
                        .HasColumnName("shift_id");

                    b.Property<decimal>("TuitionCost")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("tuition_cost");

                    b.HasKey("Id")
                        .HasName("school_fee_pkey");

                    b.HasIndex("LevelId");

                    b.HasIndex("SchoolFeeConceptId");

                    b.HasIndex("SchoolYearId");

                    b.HasIndex("ShiftId");

                    b.ToTable("school_fee", (string)null);
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.SchoolFeeConcept", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("school_fee_concepts_pkey");

                    b.HasIndex(new[] { "Name" }, "school_fee_concepts_name_key")
                        .IsUnique();

                    b.ToTable("school_fee_concepts", (string)null);
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.SchoolYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<short>("Year")
                        .HasColumnType("smallint")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("school_year_pkey");

                    b.HasIndex(new[] { "Year" }, "school_year_year_key")
                        .IsUnique();

                    b.ToTable("school_year", (string)null);
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("shifts_pkey");

                    b.HasIndex(new[] { "Name" }, "shifts_name_key")
                        .IsUnique();

                    b.ToTable("shifts", (string)null);
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.Student", b =>
                {
                    b.Property<int>("EducationalPersonId")
                        .HasColumnType("integer")
                        .HasColumnName("educational_person_id");

                    b.Property<int>("BirthUbigeoId")
                        .HasColumnType("integer")
                        .HasColumnName("birth_ubigeo_id");

                    b.Property<int?>("ChildbirthTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("childbirth_type_id");

                    b.Property<bool>("HasDisability")
                        .HasColumnType("boolean")
                        .HasColumnName("has_disability");

                    b.Property<short?>("Siblings")
                        .HasColumnType("smallint")
                        .HasColumnName("siblings");

                    b.HasKey("EducationalPersonId")
                        .HasName("students_pkey");

                    b.HasIndex("BirthUbigeoId");

                    b.HasIndex("ChildbirthTypeId");

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.StudentHome", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.Property<bool>("HasElectronicDevices")
                        .HasColumnType("boolean")
                        .HasColumnName("has_electronic_devices");

                    b.Property<bool>("HasInternetAccess")
                        .HasColumnType("boolean")
                        .HasColumnName("has_internet_access");

                    b.HasKey("StudentId")
                        .HasName("student_homes_pkey");

                    b.ToTable("student_homes", (string)null);
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.StudentState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("student_states_pkey");

                    b.HasIndex(new[] { "Name" }, "student_states_name_key")
                        .IsUnique();

                    b.ToTable("student_states", (string)null);
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.StudentStatesByYear", b =>
                {
                    b.Property<int>("SchoolYearId")
                        .HasColumnType("integer")
                        .HasColumnName("school_year_id");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.HasIndex("SchoolYearId");

                    b.HasIndex("StatusId");

                    b.HasIndex("StudentId");

                    b.ToTable("student_states_by_year", (string)null);
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.Ubigeo", b =>
                {
                    b.Property<int>("DistrictId")
                        .HasColumnType("integer")
                        .HasColumnName("district_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character(6)")
                        .HasColumnName("code")
                        .IsFixedLength();

                    b.HasKey("DistrictId")
                        .HasName("ubigeo_pkey");

                    b.ToTable("ubigeo", (string)null);
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("email");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("hashed_password");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("MaternalLastname")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("maternal_lastname");

                    b.Property<string>("Names")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("names");

                    b.Property<string>("PaternalLastname")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("paternal_lastname");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SecondLanguage", b =>
                {
                    b.Property<int>("EducationalPersonId")
                        .HasColumnType("integer")
                        .HasColumnName("educational_person_id");

                    b.Property<int>("SecondLanguageId")
                        .HasColumnType("integer")
                        .HasColumnName("second_language_id");

                    b.HasKey("EducationalPersonId", "SecondLanguageId")
                        .HasName("second_languages_pkey");

                    b.HasIndex("SecondLanguageId");

                    b.ToTable("second_languages", (string)null);
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("user_roles_pkey");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("RolePermission", b =>
                {
                    b.HasOne("SRJBackend.Infrastructure.Models.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .IsRequired()
                        .HasConstraintName("role_permissions_permission_id_fkey");

                    b.HasOne("SRJBackend.Infrastructure.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("role_permissions_role_id_fkey");
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.Disability", b =>
                {
                    b.HasOne("SRJBackend.Infrastructure.Models.DisabilityDegree", "DisabilityDegree")
                        .WithMany("Disabilities")
                        .HasForeignKey("DisabilityDegreeId")
                        .HasConstraintName("disabilities_disability_degree_id_fkey");

                    b.HasOne("SRJBackend.Infrastructure.Models.DisabilityType", "DisabilityType")
                        .WithMany("Disabilities")
                        .HasForeignKey("DisabilityTypeId")
                        .HasConstraintName("disabilities_disability_type_id_fkey");

                    b.HasOne("SRJBackend.Infrastructure.Models.Student", "Student")
                        .WithOne("Disability")
                        .HasForeignKey("SRJBackend.Infrastructure.Models.Disability", "StudentId")
                        .IsRequired()
                        .HasConstraintName("disabilities_student_id_fkey");

                    b.Navigation("DisabilityDegree");

                    b.Navigation("DisabilityType");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.District", b =>
                {
                    b.HasOne("SRJBackend.Infrastructure.Models.Province", "Province")
                        .WithMany("Districts")
                        .HasForeignKey("ProvinceId")
                        .IsRequired()
                        .HasConstraintName("district_province_id_fkey");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.EducationalPerson", b =>
                {
                    b.HasOne("SRJBackend.Infrastructure.Models.EthnicSelfIdentification", "EthnicSelfIdentification")
                        .WithMany("EducationalPeople")
                        .HasForeignKey("EthnicSelfIdentificationId")
                        .HasConstraintName("educational_person_ethnic_self_identification_id_fkey");

                    b.HasOne("SRJBackend.Infrastructure.Models.Language", "NativeLanguage")
                        .WithMany("EducationalPeople")
                        .HasForeignKey("NativeLanguageId")
                        .IsRequired()
                        .HasConstraintName("educational_person_native_language_id_fkey");

                    b.HasOne("SRJBackend.Infrastructure.Models.Person", "Person")
                        .WithOne("EducationalPerson")
                        .HasForeignKey("SRJBackend.Infrastructure.Models.EducationalPerson", "PersonId")
                        .IsRequired()
                        .HasConstraintName("educational_person_person_id_fkey");

                    b.Navigation("EthnicSelfIdentification");

                    b.Navigation("NativeLanguage");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.Enrollment", b =>
                {
                    b.HasOne("SRJBackend.Infrastructure.Models.GradeOfferingShiftSection", "GradeOfferingShiftSection")
                        .WithMany("Enrollments")
                        .HasForeignKey("GradeOfferingShiftSectionId")
                        .IsRequired()
                        .HasConstraintName("enrollment_grade_offering_shift_section_id_fkey");

                    b.HasOne("SRJBackend.Infrastructure.Models.SchoolFeeConcept", "SchoolFeeConcept")
                        .WithMany("Enrollments")
                        .HasForeignKey("SchoolFeeConceptId")
                        .IsRequired()
                        .HasConstraintName("enrollment_school_fee_concept_id_fkey");

                    b.HasOne("SRJBackend.Infrastructure.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("enrollment_student_id_fkey");

                    b.Navigation("GradeOfferingShiftSection");

                    b.Navigation("SchoolFeeConcept");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.Familiar", b =>
                {
                    b.HasOne("SRJBackend.Infrastructure.Models.EducationalPerson", "EducationalPerson")
                        .WithOne("Familiar")
                        .HasForeignKey("SRJBackend.Infrastructure.Models.Familiar", "EducationalPersonId")
                        .IsRequired()
                        .HasConstraintName("familiars_educational_person_id_fkey");

                    b.HasOne("SRJBackend.Infrastructure.Models.LevelOfEducation", "LevelOfEducation")
                        .WithMany("Familiars")
                        .HasForeignKey("LevelOfEducationId")
                        .HasConstraintName("familiars_level_of_education_id_fkey");

                    b.Navigation("EducationalPerson");

                    b.Navigation("LevelOfEducation");
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.FamiliarStudentRelationship", b =>
                {
                    b.HasOne("SRJBackend.Infrastructure.Models.Familiar", "Familiar")
                        .WithMany("FamiliarStudentRelationships")
                        .HasForeignKey("FamiliarId")
                        .IsRequired()
                        .HasConstraintName("familiar_student_relationship_familiar_id_fkey");

                    b.HasOne("SRJBackend.Infrastructure.Models.FamiliarRelationshipType", "FamiliarRelationshipType")
                        .WithMany("FamiliarStudentRelationships")
                        .HasForeignKey("FamiliarRelationshipTypeId")
                        .IsRequired()
                        .HasConstraintName("familiar_student_relationship_familiar_relationship_type_i_fkey");

                    b.HasOne("SRJBackend.Infrastructure.Models.Student", "Student")
                        .WithMany("FamiliarStudentRelationships")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("familiar_student_relationship_student_id_fkey");

                    b.Navigation("Familiar");

                    b.Navigation("FamiliarRelationshipType");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.Grade", b =>
                {
                    b.HasOne("SRJBackend.Infrastructure.Models.Level", "Level")
                        .WithMany("Grades")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("academic_grades_level_id_fkey");

                    b.Navigation("Level");
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.GradeOffering", b =>
                {
                    b.HasOne("SRJBackend.Infrastructure.Models.Grade", "Grade")
                        .WithMany("GradeOfferings")
                        .HasForeignKey("GradeId")
                        .IsRequired()
                        .HasConstraintName("grade_offerings_grade_id_fkey");

                    b.HasOne("SRJBackend.Infrastructure.Models.SchoolYear", "SchoolYear")
                        .WithMany("GradeOfferings")
                        .HasForeignKey("SchoolYearId")
                        .IsRequired()
                        .HasConstraintName("grade_offerings_school_year_id_fkey");

                    b.Navigation("Grade");

                    b.Navigation("SchoolYear");
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.GradeOfferingShift", b =>
                {
                    b.HasOne("SRJBackend.Infrastructure.Models.GradeOffering", "GradeOffering")
                        .WithMany("GradeOfferingShifts")
                        .HasForeignKey("GradeOfferingId")
                        .IsRequired()
                        .HasConstraintName("grade_offering_shifts_grade_offering_id_fkey");

                    b.HasOne("SRJBackend.Infrastructure.Models.Shift", "Shift")
                        .WithMany("GradeOfferingShifts")
                        .HasForeignKey("ShiftId")
                        .IsRequired()
                        .HasConstraintName("grade_offering_shifts_shift_id_fkey");

                    b.Navigation("GradeOffering");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.GradeOfferingShiftSection", b =>
                {
                    b.HasOne("SRJBackend.Infrastructure.Models.GradeOfferingShift", "GradeOfferingShift")
                        .WithMany("GradeOfferingShiftSections")
                        .HasForeignKey("GradeOfferingShiftId")
                        .IsRequired()
                        .HasConstraintName("grade_offering_shift_sections_grade_offering_shift_id_fkey");

                    b.Navigation("GradeOfferingShift");
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.Institution", b =>
                {
                    b.HasOne("SRJBackend.Infrastructure.Models.RucState", "RucState")
                        .WithMany("Institutions")
                        .HasForeignKey("RucStateId")
                        .IsRequired()
                        .HasConstraintName("institution_ruc_state_id_fkey");

                    b.Navigation("RucState");
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.InstitutionLevel", b =>
                {
                    b.HasOne("SRJBackend.Infrastructure.Models.Institution", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .IsRequired()
                        .HasConstraintName("institution_levels_institution_id_fkey");

                    b.HasOne("SRJBackend.Infrastructure.Models.Level", "Level")
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .IsRequired()
                        .HasConstraintName("institution_levels_level_id_fkey");

                    b.Navigation("Institution");

                    b.Navigation("Level");
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.Person", b =>
                {
                    b.HasOne("SRJBackend.Infrastructure.Models.Ubigeo", "AddressUbigeo")
                        .WithMany("People")
                        .HasForeignKey("AddressUbigeoId")
                        .IsRequired()
                        .HasConstraintName("person_address_ubigeo_id_fkey");

                    b.HasOne("SRJBackend.Infrastructure.Models.CivilState", "CivilState")
                        .WithMany("People")
                        .HasForeignKey("CivilStateId")
                        .HasConstraintName("person_civil_state_id_fkey");

                    b.HasOne("SRJBackend.Infrastructure.Models.DocumentType", "DocumentType")
                        .WithMany("People")
                        .HasForeignKey("DocumentTypeId")
                        .IsRequired()
                        .HasConstraintName("person_document_type_id_fkey");

                    b.HasOne("SRJBackend.Infrastructure.Models.Gender", "Gender")
                        .WithMany("People")
                        .HasForeignKey("GenderId")
                        .IsRequired()
                        .HasConstraintName("person_gender_id_fkey");

                    b.HasOne("SRJBackend.Infrastructure.Models.Religion", "Religion")
                        .WithMany("People")
                        .HasForeignKey("ReligionId")
                        .HasConstraintName("person_religion_id_fkey");

                    b.Navigation("AddressUbigeo");

                    b.Navigation("CivilState");

                    b.Navigation("DocumentType");

                    b.Navigation("Gender");

                    b.Navigation("Religion");
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.Province", b =>
                {
                    b.HasOne("SRJBackend.Infrastructure.Models.Department", "Department")
                        .WithMany("Provinces")
                        .HasForeignKey("DepartmentId")
                        .IsRequired()
                        .HasConstraintName("province_department_id_fkey");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.SchoolFee", b =>
                {
                    b.HasOne("SRJBackend.Infrastructure.Models.Level", "Level")
                        .WithMany("SchoolFees")
                        .HasForeignKey("LevelId")
                        .IsRequired()
                        .HasConstraintName("school_fee_level_id_fkey");

                    b.HasOne("SRJBackend.Infrastructure.Models.SchoolFeeConcept", "SchoolFeeConcept")
                        .WithMany("SchoolFees")
                        .HasForeignKey("SchoolFeeConceptId")
                        .IsRequired()
                        .HasConstraintName("school_fee_school_fee_concept_id_fkey");

                    b.HasOne("SRJBackend.Infrastructure.Models.SchoolYear", "SchoolYear")
                        .WithMany("SchoolFees")
                        .HasForeignKey("SchoolYearId")
                        .IsRequired()
                        .HasConstraintName("school_fee_school_year_id_fkey");

                    b.HasOne("SRJBackend.Infrastructure.Models.Shift", "Shift")
                        .WithMany("SchoolFees")
                        .HasForeignKey("ShiftId")
                        .IsRequired()
                        .HasConstraintName("school_fee_shift_id_fkey");

                    b.Navigation("Level");

                    b.Navigation("SchoolFeeConcept");

                    b.Navigation("SchoolYear");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.Student", b =>
                {
                    b.HasOne("SRJBackend.Infrastructure.Models.Ubigeo", "BirthUbigeo")
                        .WithMany("Students")
                        .HasForeignKey("BirthUbigeoId")
                        .IsRequired()
                        .HasConstraintName("students_birth_ubigeo_id_fkey");

                    b.HasOne("SRJBackend.Infrastructure.Models.ChildbirthType", "ChildbirthType")
                        .WithMany("Students")
                        .HasForeignKey("ChildbirthTypeId")
                        .HasConstraintName("students_childbirth_type_id_fkey");

                    b.HasOne("SRJBackend.Infrastructure.Models.EducationalPerson", "EducationalPerson")
                        .WithOne("Student")
                        .HasForeignKey("SRJBackend.Infrastructure.Models.Student", "EducationalPersonId")
                        .IsRequired()
                        .HasConstraintName("students_educational_person_id_fkey");

                    b.Navigation("BirthUbigeo");

                    b.Navigation("ChildbirthType");

                    b.Navigation("EducationalPerson");
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.StudentHome", b =>
                {
                    b.HasOne("SRJBackend.Infrastructure.Models.Student", "Student")
                        .WithOne("StudentHome")
                        .HasForeignKey("SRJBackend.Infrastructure.Models.StudentHome", "StudentId")
                        .IsRequired()
                        .HasConstraintName("student_homes_student_id_fkey");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.StudentStatesByYear", b =>
                {
                    b.HasOne("SRJBackend.Infrastructure.Models.SchoolYear", "SchoolYear")
                        .WithMany()
                        .HasForeignKey("SchoolYearId")
                        .IsRequired()
                        .HasConstraintName("student_states_by_year_school_year_id_fkey");

                    b.HasOne("SRJBackend.Infrastructure.Models.StudentState", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("student_states_by_year_status_id_fkey");

                    b.HasOne("SRJBackend.Infrastructure.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("student_states_by_year_student_id_fkey");

                    b.Navigation("SchoolYear");

                    b.Navigation("Status");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.Ubigeo", b =>
                {
                    b.HasOne("SRJBackend.Infrastructure.Models.District", "District")
                        .WithOne("Ubigeo")
                        .HasForeignKey("SRJBackend.Infrastructure.Models.Ubigeo", "DistrictId")
                        .IsRequired()
                        .HasConstraintName("ubigeo_district_id_fkey");

                    b.Navigation("District");
                });

            modelBuilder.Entity("SecondLanguage", b =>
                {
                    b.HasOne("SRJBackend.Infrastructure.Models.EducationalPerson", null)
                        .WithMany()
                        .HasForeignKey("EducationalPersonId")
                        .IsRequired()
                        .HasConstraintName("second_languages_educational_person_id_fkey");

                    b.HasOne("SRJBackend.Infrastructure.Models.Language", null)
                        .WithMany()
                        .HasForeignKey("SecondLanguageId")
                        .IsRequired()
                        .HasConstraintName("second_languages_second_language_id_fkey");
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.HasOne("SRJBackend.Infrastructure.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("user_roles_role_id_fkey");

                    b.HasOne("SRJBackend.Infrastructure.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("user_roles_user_id_fkey");
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.ChildbirthType", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.CivilState", b =>
                {
                    b.Navigation("People");
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.Department", b =>
                {
                    b.Navigation("Provinces");
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.DisabilityDegree", b =>
                {
                    b.Navigation("Disabilities");
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.DisabilityType", b =>
                {
                    b.Navigation("Disabilities");
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.District", b =>
                {
                    b.Navigation("Ubigeo");
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.DocumentType", b =>
                {
                    b.Navigation("People");
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.EducationalPerson", b =>
                {
                    b.Navigation("Familiar");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.EthnicSelfIdentification", b =>
                {
                    b.Navigation("EducationalPeople");
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.Familiar", b =>
                {
                    b.Navigation("FamiliarStudentRelationships");
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.FamiliarRelationshipType", b =>
                {
                    b.Navigation("FamiliarStudentRelationships");
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.Gender", b =>
                {
                    b.Navigation("People");
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.Grade", b =>
                {
                    b.Navigation("GradeOfferings");
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.GradeOffering", b =>
                {
                    b.Navigation("GradeOfferingShifts");
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.GradeOfferingShift", b =>
                {
                    b.Navigation("GradeOfferingShiftSections");
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.GradeOfferingShiftSection", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.Language", b =>
                {
                    b.Navigation("EducationalPeople");
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.Level", b =>
                {
                    b.Navigation("Grades");

                    b.Navigation("SchoolFees");
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.LevelOfEducation", b =>
                {
                    b.Navigation("Familiars");
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.Person", b =>
                {
                    b.Navigation("EducationalPerson");
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.Province", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.Religion", b =>
                {
                    b.Navigation("People");
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.RucState", b =>
                {
                    b.Navigation("Institutions");
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.SchoolFeeConcept", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("SchoolFees");
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.SchoolYear", b =>
                {
                    b.Navigation("GradeOfferings");

                    b.Navigation("SchoolFees");
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.Shift", b =>
                {
                    b.Navigation("GradeOfferingShifts");

                    b.Navigation("SchoolFees");
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.Student", b =>
                {
                    b.Navigation("Disability");

                    b.Navigation("Enrollments");

                    b.Navigation("FamiliarStudentRelationships");

                    b.Navigation("StudentHome");
                });

            modelBuilder.Entity("SRJBackend.Infrastructure.Models.Ubigeo", b =>
                {
                    b.Navigation("People");

                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
